# backend-compose.yml
version: "3.9"
services:
  redis:
    image: redis:alpine
    restart: always

  worker:
    image: dockersamples/examplevotingapp_worker
    environment:
      REDIS_HOST: "localhost"
      DB_HOST: "<PRIVATE_IP_OF_DB_EC2>"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    restart: always
